// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/node.proto

// Node-to-node RPC. Generated Go lives in internal/api/nodepb; regenerate
// with `make proto` after editing this file.

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	HintedFor     string                 `protobuf:"bytes,6,opt,name=hinted_for,json=hintedFor,proto3" json:"hinted_for,omitempty"`
	Deleted       bool                   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	WrittenUnixMs int64                  `protobuf:"varint,8,opt,name=written_unix_ms,json=writtenUnixMs,proto3" json:"written_unix_ms,omitempty"`
	ContentType   string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectMeta) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ObjectMeta) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *ObjectMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectMeta) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ObjectMeta) GetHintedFor() string {
	if x != nil {
		return x.HintedFor
	}
	return ""
}

func (x *ObjectMeta) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *ObjectMeta) GetWrittenUnixMs() int64 {
	if x != nil {
		return x.WrittenUnixMs
	}
	return 0
}

func (x *ObjectMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateRequest) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReplicateRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ReplicateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReplicateResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Stored bool                   `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	// What the replica holds after the call. An ack means current >= meta.
	Current       *ObjectMeta `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateResponse) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *ReplicateResponse) GetCurrent() *ObjectMeta {
	if x != nil {
		return x.Current
	}
	return nil
}

type GetReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	WithBody      bool                   `protobuf:"varint,2,opt,name=with_body,json=withBody,proto3" json:"with_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaRequest) Reset() {
	*x = GetReplicaRequest{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaRequest) ProtoMessage() {}

func (x *GetReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaRequest.ProtoReflect.Descriptor instead.
func (*GetReplicaRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetReplicaRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetReplicaRequest) GetWithBody() bool {
	if x != nil {
		return x.WithBody
	}
	return false
}

type GetReplicaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Meta  *ObjectMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Body  []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// The stored bytes no longer match the stored SHA-256.
	Corrupt bool `protobuf:"varint,4,opt,name=corrupt,proto3" json:"corrupt,omitempty"`
	// The copy is a parked hint, not a primary replica.
	Hinted        bool `protobuf:"varint,5,opt,name=hinted,proto3" json:"hinted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaResponse) Reset() {
	*x = GetReplicaResponse{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaResponse) ProtoMessage() {}

func (x *GetReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaResponse.ProtoReflect.Descriptor instead.
func (*GetReplicaResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *GetReplicaResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetReplicaResponse) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetReplicaResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetReplicaResponse) GetCorrupt() bool {
	if x != nil {
		return x.Corrupt
	}
	return false
}

func (x *GetReplicaResponse) GetHinted() bool {
	if x != nil {
		return x.Hinted
	}
	return false
}

type RepairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairRequest) Reset() {
	*x = RepairRequest{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairRequest) ProtoMessage() {}

func (x *RepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairRequest.ProtoReflect.Descriptor instead.
func (*RepairRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *RepairRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RepairRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RepairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerVersion uint64                 `protobuf:"varint,1,opt,name=winner_version,json=winnerVersion,proto3" json:"winner_version,omitempty"`
	Pushed        []string               `protobuf:"bytes,2,rep,name=pushed,proto3" json:"pushed,omitempty"`
	Dropped       []string               `protobuf:"bytes,3,rep,name=dropped,proto3" json:"dropped,omitempty"`
	Corrupt       []string               `protobuf:"bytes,4,rep,name=corrupt,proto3" json:"corrupt,omitempty"`
	TookMicros    int64                  `protobuf:"varint,5,opt,name=took_micros,json=tookMicros,proto3" json:"took_micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairResponse) Reset() {
	*x = RepairResponse{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairResponse) ProtoMessage() {}

func (x *RepairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairResponse.ProtoReflect.Descriptor instead.
func (*RepairResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *RepairResponse) GetWinnerVersion() uint64 {
	if x != nil {
		return x.WinnerVersion
	}
	return 0
}

func (x *RepairResponse) GetPushed() []string {
	if x != nil {
		return x.Pushed
	}
	return nil
}

func (x *RepairResponse) GetDropped() []string {
	if x != nil {
		return x.Dropped
	}
	return nil
}

func (x *RepairResponse) GetCorrupt() []string {
	if x != nil {
		return x.Corrupt
	}
	return nil
}

func (x *RepairResponse) GetTookMicros() int64 {
	if x != nil {
		return x.TookMicros
	}
	return 0
}

type HintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Meta          *ObjectMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintRequest) Reset() {
	*x = HintRequest{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintRequest) ProtoMessage() {}

func (x *HintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintRequest.ProtoReflect.Descriptor instead.
func (*HintRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *HintRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *HintRequest) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *HintRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintResponse) Reset() {
	*x = HintResponse{}
	mi := &file_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintResponse) ProtoMessage() {}

func (x *HintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintResponse.ProtoReflect.Descriptor instead.
func (*HintResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *HintResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RingSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingSnapshotRequest) Reset() {
	*x = RingSnapshotRequest{}
	mi := &file_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingSnapshotRequest) ProtoMessage() {}

func (x *RingSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RingSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{9}
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	RingVersion   uint64                 `protobuf:"varint,4,opt,name=ring_version,json=ringVersion,proto3" json:"ring_version,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,5,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	HttpAddr      string                 `protobuf:"bytes,6,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,7,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	InRing        bool                   `protobuf:"varint,8,opt,name=in_ring,json=inRing,proto3" json:"in_ring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Member) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Member) GetRingVersion() uint64 {
	if x != nil {
		return x.RingVersion
	}
	return 0
}

func (x *Member) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *Member) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *Member) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *Member) GetInRing() bool {
	if x != nil {
		return x.InRing
	}
	return false
}

type RingSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RingVersion   uint64                 `protobuf:"varint,1,opt,name=ring_version,json=ringVersion,proto3" json:"ring_version,omitempty"`
	Members       []*Member              `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	RingDigest    string                 `protobuf:"bytes,3,opt,name=ring_digest,json=ringDigest,proto3" json:"ring_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingSnapshotResponse) Reset() {
	*x = RingSnapshotResponse{}
	mi := &file_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingSnapshotResponse) ProtoMessage() {}

func (x *RingSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RingSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *RingSnapshotResponse) GetRingVersion() uint64 {
	if x != nil {
		return x.RingVersion
	}
	return 0
}

func (x *RingSnapshotResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RingSnapshotResponse) GetRingDigest() string {
	if x != nil {
		return x.RingDigest
	}
	return ""
}

type ListReplicasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicasRequest) Reset() {
	*x = ListReplicasRequest{}
	mi := &file_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicasRequest) ProtoMessage() {}

func (x *ListReplicasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicasRequest.ProtoReflect.Descriptor instead.
func (*ListReplicasRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{12}
}

type ListReplicasResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Objects []*ObjectMeta          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	// Parked hints. hinted_for names the node each hint is waiting for.
	Hints []*ObjectMeta `protobuf:"bytes,2,rep,name=hints,proto3" json:"hints,omitempty"`
	// Keys whose bytes an operator flipped and no check has caught yet.
	Tampered      []string `protobuf:"bytes,3,rep,name=tampered,proto3" json:"tampered,omitempty"`
	Bytes         uint64   `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicasResponse) Reset() {
	*x = ListReplicasResponse{}
	mi := &file_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicasResponse) ProtoMessage() {}

func (x *ListReplicasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicasResponse.ProtoReflect.Descriptor instead.
func (*ListReplicasResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *ListReplicasResponse) GetObjects() []*ObjectMeta {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListReplicasResponse) GetHints() []*ObjectMeta {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *ListReplicasResponse) GetTampered() []string {
	if x != nil {
		return x.Tampered
	}
	return nil
}

func (x *ListReplicasResponse) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         uint64                 `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *EventsRequest) GetSince() uint64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *EventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,2,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{15}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *Event) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Event) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *EventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CorruptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorruptRequest) Reset() {
	*x = CorruptRequest{}
	mi := &file_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorruptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorruptRequest) ProtoMessage() {}

func (x *CorruptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorruptRequest.ProtoReflect.Descriptor instead.
func (*CorruptRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *CorruptRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CorruptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Corrupted     bool                   `protobuf:"varint,1,opt,name=corrupted,proto3" json:"corrupted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorruptResponse) Reset() {
	*x = CorruptResponse{}
	mi := &file_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorruptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorruptResponse) ProtoMessage() {}

func (x *CorruptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorruptResponse.ProtoReflect.Descriptor instead.
func (*CorruptResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{18}
}

func (x *CorruptResponse) GetCorrupted() bool {
	if x != nil {
		return x.Corrupted
	}
	return false
}

type ScrubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrubRequest) Reset() {
	*x = ScrubRequest{}
	mi := &file_proto_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrubRequest) ProtoMessage() {}

func (x *ScrubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrubRequest.ProtoReflect.Descriptor instead.
func (*ScrubRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{19}
}

type ScrubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checked       uint64                 `protobuf:"varint,1,opt,name=checked,proto3" json:"checked,omitempty"`
	Mismatches    uint64                 `protobuf:"varint,2,opt,name=mismatches,proto3" json:"mismatches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrubResponse) Reset() {
	*x = ScrubResponse{}
	mi := &file_proto_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrubResponse) ProtoMessage() {}

func (x *ScrubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrubResponse.ProtoReflect.Descriptor instead.
func (*ScrubResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{20}
}

func (x *ScrubResponse) GetChecked() uint64 {
	if x != nil {
		return x.Checked
	}
	return 0
}

func (x *ScrubResponse) GetMismatches() uint64 {
	if x != nil {
		return x.Mismatches
	}
	return 0
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\n" +
	"athanor.v1\"\x84\x02\n" +
	"\n" +
	"ObjectMeta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12\x1d\n" +
	"\n" +
	"hinted_for\x18\x06 \x01(\tR\thintedFor\x12\x18\n" +
	"\adeleted\x18\a \x01(\bR\adeleted\x12&\n" +
	"\x0fwritten_unix_ms\x18\b \x01(\x03R\rwrittenUnixMs\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\"j\n" +
	"\x10ReplicateRequest\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x16.athanor.v1.ObjectMetaR\x04meta\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"]\n" +
	"\x11ReplicateResponse\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\x120\n" +
	"\acurrent\x18\x02 \x01(\v2\x16.athanor.v1.ObjectMetaR\acurrent\"B\n" +
	"\x11GetReplicaRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\twith_body\x18\x02 \x01(\bR\bwithBody\"\x9c\x01\n" +
	"\x12GetReplicaResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.athanor.v1.ObjectMetaR\x04meta\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x18\n" +
	"\acorrupt\x18\x04 \x01(\bR\acorrupt\x12\x16\n" +
	"\x06hinted\x18\x05 \x01(\bR\x06hinted\"9\n" +
	"\rRepairRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa4\x01\n" +
	"\x0eRepairResponse\x12%\n" +
	"\x0ewinner_version\x18\x01 \x01(\x04R\rwinnerVersion\x12\x16\n" +
	"\x06pushed\x18\x02 \x03(\tR\x06pushed\x12\x18\n" +
	"\adropped\x18\x03 \x03(\tR\adropped\x12\x18\n" +
	"\acorrupt\x18\x04 \x03(\tR\acorrupt\x12\x1f\n" +
	"\vtook_micros\x18\x05 \x01(\x03R\n" +
	"tookMicros\"e\n" +
	"\vHintRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.athanor.v1.ObjectMetaR\x04meta\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"*\n" +
	"\fHintResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x15\n" +
	"\x13RingSnapshotRequest\"\xd9\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fring_version\x18\x04 \x01(\x04R\vringVersion\x12\x1b\n" +
	"\tgrpc_addr\x18\x05 \x01(\tR\bgrpcAddr\x12\x1b\n" +
	"\thttp_addr\x18\x06 \x01(\tR\bhttpAddr\x12\x1d\n" +
	"\n" +
	"public_url\x18\a \x01(\tR\tpublicUrl\x12\x17\n" +
	"\ain_ring\x18\b \x01(\bR\x06inRing\"\x88\x01\n" +
	"\x14RingSnapshotResponse\x12!\n" +
	"\fring_version\x18\x01 \x01(\x04R\vringVersion\x12,\n" +
	"\amembers\x18\x02 \x03(\v2\x12.athanor.v1.MemberR\amembers\x12\x1f\n" +
	"\vring_digest\x18\x03 \x01(\tR\n" +
	"ringDigest\"\x15\n" +
	"\x13ListReplicasRequest\"\xa8\x01\n" +
	"\x14ListReplicasResponse\x120\n" +
	"\aobjects\x18\x01 \x03(\v2\x16.athanor.v1.ObjectMetaR\aobjects\x12,\n" +
	"\x05hints\x18\x02 \x03(\v2\x16.athanor.v1.ObjectMetaR\x05hints\x12\x1a\n" +
	"\btampered\x18\x03 \x03(\tR\btampered\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\x04R\x05bytes\";\n" +
	"\rEventsRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x04R\x05since\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\x93\x02\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x02 \x01(\x03R\batUnixMs\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x125\n" +
	"\x06fields\x18\b \x03(\v2\x1d.athanor.v1.Event.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x0eEventsResponse\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.athanor.v1.EventR\x06events\"\"\n" +
	"\x0eCorruptRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"/\n" +
	"\x0fCorruptResponse\x12\x1c\n" +
	"\tcorrupted\x18\x01 \x01(\bR\tcorrupted\"\x0e\n" +
	"\fScrubRequest\"I\n" +
	"\rScrubResponse\x12\x18\n" +
	"\achecked\x18\x01 \x01(\x04R\achecked\x12\x1e\n" +
	"\n" +
	"mismatches\x18\x02 \x01(\x04R\n" +
	"mismatches2\x82\x05\n" +
	"\x04Node\x12H\n" +
	"\tReplicate\x12\x1c.athanor.v1.ReplicateRequest\x1a\x1d.athanor.v1.ReplicateResponse\x12K\n" +
	"\n" +
	"GetReplica\x12\x1d.athanor.v1.GetReplicaRequest\x1a\x1e.athanor.v1.GetReplicaResponse\x12?\n" +
	"\x06Repair\x12\x19.athanor.v1.RepairRequest\x1a\x1a.athanor.v1.RepairResponse\x129\n" +
	"\x04Hint\x12\x17.athanor.v1.HintRequest\x1a\x18.athanor.v1.HintResponse\x12Q\n" +
	"\fRingSnapshot\x12\x1f.athanor.v1.RingSnapshotRequest\x1a .athanor.v1.RingSnapshotResponse\x12Q\n" +
	"\fListReplicas\x12\x1f.athanor.v1.ListReplicasRequest\x1a .athanor.v1.ListReplicasResponse\x12?\n" +
	"\x06Events\x12\x19.athanor.v1.EventsRequest\x1a\x1a.athanor.v1.EventsResponse\x12B\n" +
	"\aCorrupt\x12\x1a.athanor.v1.CorruptRequest\x1a\x1b.athanor.v1.CorruptResponse\x12<\n" +
	"\x05Scrub\x12\x18.athanor.v1.ScrubRequest\x1a\x19.athanor.v1.ScrubResponseB4Z2github.com/Arjun-Walia/Athanor/internal/api/nodepbb\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_node_proto_goTypes = []any{
	(*ObjectMeta)(nil),           // 0: athanor.v1.ObjectMeta
	(*ReplicateRequest)(nil),     // 1: athanor.v1.ReplicateRequest
	(*ReplicateResponse)(nil),    // 2: athanor.v1.ReplicateResponse
	(*GetReplicaRequest)(nil),    // 3: athanor.v1.GetReplicaRequest
	(*GetReplicaResponse)(nil),   // 4: athanor.v1.GetReplicaResponse
	(*RepairRequest)(nil),        // 5: athanor.v1.RepairRequest
	(*RepairResponse)(nil),       // 6: athanor.v1.RepairResponse
	(*HintRequest)(nil),          // 7: athanor.v1.HintRequest
	(*HintResponse)(nil),         // 8: athanor.v1.HintResponse
	(*RingSnapshotRequest)(nil),  // 9: athanor.v1.RingSnapshotRequest
	(*Member)(nil),               // 10: athanor.v1.Member
	(*RingSnapshotResponse)(nil), // 11: athanor.v1.RingSnapshotResponse
	(*ListReplicasRequest)(nil),  // 12: athanor.v1.ListReplicasRequest
	(*ListReplicasResponse)(nil), // 13: athanor.v1.ListReplicasResponse
	(*EventsRequest)(nil),        // 14: athanor.v1.EventsRequest
	(*Event)(nil),                // 15: athanor.v1.Event
	(*EventsResponse)(nil),       // 16: athanor.v1.EventsResponse
	(*CorruptRequest)(nil),       // 17: athanor.v1.CorruptRequest
	(*CorruptResponse)(nil),      // 18: athanor.v1.CorruptResponse
	(*ScrubRequest)(nil),         // 19: athanor.v1.ScrubRequest
	(*ScrubResponse)(nil),        // 20: athanor.v1.ScrubResponse
	nil,                          // 21: athanor.v1.Event.FieldsEntry
}
var file_proto_node_proto_depIdxs = []int32{
	0,  // 0: athanor.v1.ReplicateRequest.meta:type_name -> athanor.v1.ObjectMeta
	0,  // 1: athanor.v1.ReplicateResponse.current:type_name -> athanor.v1.ObjectMeta
	0,  // 2: athanor.v1.GetReplicaResponse.meta:type_name -> athanor.v1.ObjectMeta
	0,  // 3: athanor.v1.HintRequest.meta:type_name -> athanor.v1.ObjectMeta
	10, // 4: athanor.v1.RingSnapshotResponse.members:type_name -> athanor.v1.Member
	0,  // 5: athanor.v1.ListReplicasResponse.objects:type_name -> athanor.v1.ObjectMeta
	0,  // 6: athanor.v1.ListReplicasResponse.hints:type_name -> athanor.v1.ObjectMeta
	21, // 7: athanor.v1.Event.fields:type_name -> athanor.v1.Event.FieldsEntry
	15, // 8: athanor.v1.EventsResponse.events:type_name -> athanor.v1.Event
	1,  // 9: athanor.v1.Node.Replicate:input_type -> athanor.v1.ReplicateRequest
	3,  // 10: athanor.v1.Node.GetReplica:input_type -> athanor.v1.GetReplicaRequest
	5,  // 11: athanor.v1.Node.Repair:input_type -> athanor.v1.RepairRequest
	7,  // 12: athanor.v1.Node.Hint:input_type -> athanor.v1.HintRequest
	9,  // 13: athanor.v1.Node.RingSnapshot:input_type -> athanor.v1.RingSnapshotRequest
	12, // 14: athanor.v1.Node.ListReplicas:input_type -> athanor.v1.ListReplicasRequest
	14, // 15: athanor.v1.Node.Events:input_type -> athanor.v1.EventsRequest
	17, // 16: athanor.v1.Node.Corrupt:input_type -> athanor.v1.CorruptRequest
	19, // 17: athanor.v1.Node.Scrub:input_type -> athanor.v1.ScrubRequest
	2,  // 18: athanor.v1.Node.Replicate:output_type -> athanor.v1.ReplicateResponse
	4,  // 19: athanor.v1.Node.GetReplica:output_type -> athanor.v1.GetReplicaResponse
	6,  // 20: athanor.v1.Node.Repair:output_type -> athanor.v1.RepairResponse
	8,  // 21: athanor.v1.Node.Hint:output_type -> athanor.v1.HintResponse
	11, // 22: athanor.v1.Node.RingSnapshot:output_type -> athanor.v1.RingSnapshotResponse
	13, // 23: athanor.v1.Node.ListReplicas:output_type -> athanor.v1.ListReplicasResponse
	16, // 24: athanor.v1.Node.Events:output_type -> athanor.v1.EventsResponse
	18, // 25: athanor.v1.Node.Corrupt:output_type -> athanor.v1.CorruptResponse
	20, // 26: athanor.v1.Node.Scrub:output_type -> athanor.v1.ScrubResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
