// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: proto/node.proto

// Node-to-node RPC. Generated Go lives in internal/api/nodepb; regenerate
// with `make proto` after editing this file.

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_Replicate_FullMethodName    = "/athanor.v1.Node/Replicate"
	Node_GetReplica_FullMethodName   = "/athanor.v1.Node/GetReplica"
	Node_Repair_FullMethodName       = "/athanor.v1.Node/Repair"
	Node_Hint_FullMethodName         = "/athanor.v1.Node/Hint"
	Node_RingSnapshot_FullMethodName = "/athanor.v1.Node/RingSnapshot"
	Node_ListReplicas_FullMethodName = "/athanor.v1.Node/ListReplicas"
	Node_Events_FullMethodName       = "/athanor.v1.Node/Events"
	Node_Corrupt_FullMethodName      = "/athanor.v1.Node/Corrupt"
	Node_Scrub_FullMethodName        = "/athanor.v1.Node/Scrub"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	// Store a primary replica if it is newer than (or heals) the local copy.
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
	// Read a replica. Falls back to a parked hint when no primary copy exists.
	GetReplica(ctx context.Context, in *GetReplicaRequest, opts ...grpc.CallOption) (*GetReplicaResponse, error)
	// Run the one Repair(key) path with this node as the repair coordinator.
	Repair(ctx context.Context, in *RepairRequest, opts ...grpc.CallOption) (*RepairResponse, error)
	// Park a write for a preferred node that is unreachable (sloppy quorum).
	Hint(ctx context.Context, in *HintRequest, opts ...grpc.CallOption) (*HintResponse, error)
	// This node's gossiped membership and ring version.
	RingSnapshot(ctx context.Context, in *RingSnapshotRequest, opts ...grpc.CallOption) (*RingSnapshotResponse, error)
	// Control-plane helpers used by rebalance and the dashboard.
	ListReplicas(ctx context.Context, in *ListReplicasRequest, opts ...grpc.CallOption) (*ListReplicasResponse, error)
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*EventsResponse, error)
	Corrupt(ctx context.Context, in *CorruptRequest, opts ...grpc.CallOption) (*CorruptResponse, error)
	Scrub(ctx context.Context, in *ScrubRequest, opts ...grpc.CallOption) (*ScrubResponse, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, Node_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetReplica(ctx context.Context, in *GetReplicaRequest, opts ...grpc.CallOption) (*GetReplicaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicaResponse)
	err := c.cc.Invoke(ctx, Node_GetReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Repair(ctx context.Context, in *RepairRequest, opts ...grpc.CallOption) (*RepairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepairResponse)
	err := c.cc.Invoke(ctx, Node_Repair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Hint(ctx context.Context, in *HintRequest, opts ...grpc.CallOption) (*HintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HintResponse)
	err := c.cc.Invoke(ctx, Node_Hint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) RingSnapshot(ctx context.Context, in *RingSnapshotRequest, opts ...grpc.CallOption) (*RingSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RingSnapshotResponse)
	err := c.cc.Invoke(ctx, Node_RingSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ListReplicas(ctx context.Context, in *ListReplicasRequest, opts ...grpc.CallOption) (*ListReplicasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReplicasResponse)
	err := c.cc.Invoke(ctx, Node_ListReplicas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, Node_Events_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Corrupt(ctx context.Context, in *CorruptRequest, opts ...grpc.CallOption) (*CorruptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorruptResponse)
	err := c.cc.Invoke(ctx, Node_Corrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Scrub(ctx context.Context, in *ScrubRequest, opts ...grpc.CallOption) (*ScrubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrubResponse)
	err := c.cc.Invoke(ctx, Node_Scrub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
type NodeServer interface {
	// Store a primary replica if it is newer than (or heals) the local copy.
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
	// Read a replica. Falls back to a parked hint when no primary copy exists.
	GetReplica(context.Context, *GetReplicaRequest) (*GetReplicaResponse, error)
	// Run the one Repair(key) path with this node as the repair coordinator.
	Repair(context.Context, *RepairRequest) (*RepairResponse, error)
	// Park a write for a preferred node that is unreachable (sloppy quorum).
	Hint(context.Context, *HintRequest) (*HintResponse, error)
	// This node's gossiped membership and ring version.
	RingSnapshot(context.Context, *RingSnapshotRequest) (*RingSnapshotResponse, error)
	// Control-plane helpers used by rebalance and the dashboard.
	ListReplicas(context.Context, *ListReplicasRequest) (*ListReplicasResponse, error)
	Events(context.Context, *EventsRequest) (*EventsResponse, error)
	Corrupt(context.Context, *CorruptRequest) (*CorruptResponse, error)
	Scrub(context.Context, *ScrubRequest) (*ScrubResponse, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedNodeServer) GetReplica(context.Context, *GetReplicaRequest) (*GetReplicaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReplica not implemented")
}
func (UnimplementedNodeServer) Repair(context.Context, *RepairRequest) (*RepairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Repair not implemented")
}
func (UnimplementedNodeServer) Hint(context.Context, *HintRequest) (*HintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hint not implemented")
}
func (UnimplementedNodeServer) RingSnapshot(context.Context, *RingSnapshotRequest) (*RingSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RingSnapshot not implemented")
}
func (UnimplementedNodeServer) ListReplicas(context.Context, *ListReplicasRequest) (*ListReplicasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReplicas not implemented")
}
func (UnimplementedNodeServer) Events(context.Context, *EventsRequest) (*EventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedNodeServer) Corrupt(context.Context, *CorruptRequest) (*CorruptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Corrupt not implemented")
}
func (UnimplementedNodeServer) Scrub(context.Context, *ScrubRequest) (*ScrubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scrub not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call panics, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetReplica(ctx, req.(*GetReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Repair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Repair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Repair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Repair(ctx, req.(*RepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Hint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Hint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Hint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Hint(ctx, req.(*HintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_RingSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RingSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).RingSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_RingSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).RingSnapshot(ctx, req.(*RingSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ListReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplicasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ListReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_ListReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ListReplicas(ctx, req.(*ListReplicasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Events_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Events(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Events_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Events(ctx, req.(*EventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Corrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorruptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Corrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Corrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Corrupt(ctx, req.(*CorruptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Scrub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Scrub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Scrub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Scrub(ctx, req.(*ScrubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "athanor.v1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Replicate",
			Handler:    _Node_Replicate_Handler,
		},
		{
			MethodName: "GetReplica",
			Handler:    _Node_GetReplica_Handler,
		},
		{
			MethodName: "Repair",
			Handler:    _Node_Repair_Handler,
		},
		{
			MethodName: "Hint",
			Handler:    _Node_Hint_Handler,
		},
		{
			MethodName: "RingSnapshot",
			Handler:    _Node_RingSnapshot_Handler,
		},
		{
			MethodName: "ListReplicas",
			Handler:    _Node_ListReplicas_Handler,
		},
		{
			MethodName: "Events",
			Handler:    _Node_Events_Handler,
		},
		{
			MethodName: "Corrupt",
			Handler:    _Node_Corrupt_Handler,
		},
		{
			MethodName: "Scrub",
			Handler:    _Node_Scrub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/node.proto",
}
